### ISSUE TITLE
Please help me（empty range for randrange() (0, 0, 0)）

### ISSUE THREAD

**Issue by Jioazathoth** [morimoris/keras_srcnn#3]
I am a college student and I want to try your project.  I have an error in generating data, but I can't find a solution on the network. Please help me

**empty range for randrange() (0, 0, 0)**

**Comment by Jioazathoth** [comment]
ValueError                                Traceback (most recent call last)
~\Desktop\keras_SRCNN-master\main.py in <module>
     33     if args.mode == 'train_datacreate': #学習用データセットの生成
     34         datacreate = data_create.datacreate()
---> 35         train_x, train_y = datacreate.datacreate(args.train_path,       #切り取る動画のpath
     36                                             args.train_dataset_num,     #データセットの生成数
     37                                             args.train_cut_num,         #1枚の画像から生成するデータの数

~\Desktop\keras_SRCNN-master\data_create.py in datacreate(self, img_path, data_number, cut_frame, HR_height, HR_width)
     27 
     28         while self.num < data_number:
---> 29             photo_num = random.randint(0, len(files) - 1)
     30             img = cv2.imread(files[photo_num])
     31             height, width = img.shape[:2]

~\anaconda3\lib\random.py in randint(self, a, b)
    246         """
    247 
--> 248         return self.randrange(a, b+1)
    249 
    250     def _randbelow_with_getrandbits(self, n):

~\anaconda3\lib\random.py in randrange(self, start, stop, step, _int)
    224             return istart + self._randbelow(width)
    225         if step == 1:
--> 226             raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
    227 
    228         # Non-unit step argument supplied.

ValueError: empty range for randrange() (0, 0, 0)

**Comment by morimoris** [comment]
Thank you for your message.
We think this is due to the fact that the value of random.randint(0, len(files)-1) is not included.
I need you to confirm that the path "args.train_path" is correct.

**Comment by Jioazathoth** [comment]
Thank you for your reply, but it's embarrassing that I made a new mistake

**Comment by Jioazathoth** [comment]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\Desktop\keras_SRCNN-master\main.py in <module>
     33     if args.mode == 'train_datacreate': #学習用データセットの生成
     34         datacreate = data_create.datacreate()
---> 35         train_x, train_y = datacreate.datacreate(args.train_path,
     36                                             args.train_width)   
     37         path = "train_data_list"

TypeError: datacreate() missing 3 required positional arguments: 'cut_frame', 'HR_height', and 'HR_width'

**Comment by morimoris** [comment]
Thank you.
In datacreate.py(line 12~17),

"def datacreate" 

have set five variables.

However, your code in main.py(line 35~36) set two variables.
If you want to use only two variables, you need to change the code of the function datacreate in datacreate.py.

**Comment by Jioazathoth** [comment]
Thank you very much for your guidance. I have successfully generated the training model and started the training. But there was another mistake

**Comment by Jioazathoth** [comment]
ResourceExhaustedError:  OOM when allocating tensor with shape[16,64,700,700] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node functional_1/conv2d/Conv2D (defined at C:\Users\Jiomangund\Desktop\keras_SRCNN-master\main.py:81) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_train_function_780]

Function call stack:
train_function

**Comment by Jioazathoth** [comment]
My GPU is 1050  2G,so which variables shold be changed? or may i shold use the tensorflow-cpu?

**Comment by Jioazathoth** [comment]
I successfully completed your project!!! 
Thank you for your guidance, but maybe this project is too difficult for me. I should learn the basic skills of Python first. 
Thank you again for your guidance

**Comment by morimoris** [comment]
I'm glad you were able to do it!
It's pretty much my own way of writing, so you may want to try different things.
I thought it would be a good idea to write the runtime environment, so I'll add it to github.

Finally, thanks for asking the question!
