### ISSUE TITLE
About the license

### ISSUE THREAD

**Issue by 9uanhuo** [morimoris/keras_srcnn#4]
Hi, could you declare the license that this project will use? I'd like to request your permission to modify your code to  meet the needs of my course paper, of course, I will indicate your project address. Anyway, all your choice will be respected, so I will not use you code for my course paper without your permission.
Looking forward to your reply : )

**Comment by morimoris** [comment]
Thank you for your message!

You are welcome to use this code.
However, please be aware that this code is based on SRCNN paper.

**Comment by 9uanhuo** [comment]
Thanks for your permission!
btw, I am reading the same paper mentioned in your blog : D , and thank for your kindness again!
